### ISSUE TITLE
uvcvideo doesn't seem to work built in

### ISSUE THREAD

**Issue by mikey0000** [ayufan-pine64/linux-3.10#1]
changing these two values to modules might work but its how its configured in traditional linux configs.

CONFIG_VIDEOBUF2_CORE=m
CONFIG_VIDEOBUF2_MEMOPS=m
CONFIG_VIDEOBUF2_VMALLOC=m
CONFIG_MEDIA_USB_SUPPORT=y
CONFIG_USB_VIDEO_CLASS=m
CONFIG_USB_VIDEO_CLASS_INPUT_EDEV=y

also we should enable usb midi audio as well
CONFIG_SND_USB_AUDIO=y

--> now picks up my mic from my camera

however I'm not sure which kernel is part of the device tree and it doesn't accept the uvcmodule provided, I did manage to get slightly closer with a built module from this branch

as always, I'm in the process of validating this but thought I'd open discussion.

So I've managed to build this particular kernel with the uvcvudeo as a module and the modules themselves work but they aren't being loaded when android detects the webcam, this did work on stock 5.1.1 I'm lost on this issue unless its due to some other allwinner change in frameworks.

```
uvcvideo: Found UVC 1.00 device HD Webcam C615 (046d:082c)
input: HD Webcam C615 as /devices/soc.0/1c1a000.ehci0-controller/usb1/1-1/1-1:1.2/input/input7
usbcore: registered new interface driver uvcvideo
USB Video Class driver (1.1.1)
```

dmesg output after loading the module

**Comment by ayufan** [comment]
I do not have UVC camera so I can't test it, but it seems that 5M does work properly.
